<!DOCTYPE html>
<html lang="fr">
<head>
	<meta charset="UTF-8">
	<title>Mon Blog</title>
	<link rel="stylesheet" href="styles.css">
	<link href='http://fonts.googleapis.com/css?family=Droid+Serif' rel='stylesheet' type='text/css'>
</head>
<body>

	<div>
		
		<a href="admin.php?connexion=true" class="red" >>> DÉCONNEXION</a>
	
		<article>
		<h1>Nouveau commentaire</h1>
			<form action="createcomment.php?id=<?php echo $_GET["id"] ?>" method="post">
			<ul>
				<li><textarea name="content" rows="40"></textarea></li>
				<li><input type="submit" name="submit" value="VALIDER"</li>
			</ul>
		</form>
		</article>
	</div>
</body>
</html>