<!DOCTYPE html>
<html lang="fr">
<head>
	<meta charset="UTF-8">
	<title>Mon Blog</title>
	<link rel="stylesheet" href="styles.css">
	<link href='http://fonts.googleapis.com/css?family=Droid+Serif' rel='stylesheet' type='text/css'>
</head>
<body>

	<div>
		
		<?php include "nav.php" ?>

		<h1><a href="index.php">Sciences politiques <br>& Économie générale</a></h1>
	
		<article>
		
		<h2>Nouveau commentaire</h2>
			<form action="createcomment.php?id=<?php echo $_GET["id"] ?>" method="post">
			<ul>
				<li><textarea name="content" rows="30" required></textarea></li>
				<li><input type="submit" name="submit" value="VALIDER"</li>
			</ul>
		</form>
		</article>
	</div>
</body>
</html>