<!DOCTYPE html>
<html lang="fr">
<head>
	<meta charset="UTF-8">
	<title>Mon Blog</title>
	<link rel="stylesheet" href="styles.css">
	<link href='http://fonts.googleapis.com/css?family=Droid+Serif' rel='stylesheet' type='text/css'>
</head>
<body>
	<div>
		<article>
		<h1>Nouvel article</h1>
			<form action="createpost.php" method="post">
			<ul>
				<li><input type="text" name="title" value="Titre"></li>
				<li><textarea name="content" rows="40"></textarea></li>
				<li><input type="submit" name="submit" value="VALIDER"</li>
			</ul>
		</form>
		</article>
	</div>
</body>
</html>