<!DOCTYPE html>
<html lang="fr">
<head>
	<meta charset="UTF-8">
	<title>Mon Blog</title>
	<link rel="stylesheet" href="styles.css">
	<link href='http://fonts.googleapis.com/css?family=Droid+Serif' rel='stylesheet' type='text/css'>
</head>
<body>
	<div>

		<?php include "nav.php" ?>

		
		<article>
		<h1>Suppression d'un article</h1>
			<ul>
				<li>Es-tu sûr(e) de vouloir supprimer l'article : </li>
				<li><h2><a href="post.php?id=<?php echo $post["id"] ?>"><?php echo $postTitle ?> ?</a></h2></li>
				<li>Posté le <?php echo date("d/m/Y",strtotime($post["date_create"])) ?> par <?php echo $posts->getAuthorName($post["id"]) ?></li>
				 <li><?php echo $comments->getNumberOfComments($post["id"]) ?> commentaires.</li>
			</ul>
			
			<a href="deletepost.php?id=<?= $post['id'] ?>&confirm=true" class="red">OUI</a>
			<a href="admin.php" class="green">NON</a>
		</article>

	</div>
</body>
</html>