<!DOCTYPE html>
<html lang="fr">
<head>
	<meta charset="UTF-8">
	<title>Mon Blog</title>
	<link rel="stylesheet" href="styles.css">
	<link href='http://fonts.googleapis.com/css?family=Droid+Serif' rel='stylesheet' type='text/css'>
</head>
<body>

	<div>
		
		<?php include "nav.php" ?>
		
		<h1>Modifier un article</h1>
		
		<article>

				<form method="post"  enctype="multipart/form-data" action="editpost.php">

					<h2>Choisir une nouvelle illustration :</h2>

				    <input type="file" name ="picture" id="upload-id">

					<h2>Modification du texte :</h2>

					<ul>
						<li><input type="text" name="title" value="<?php echo $originalTitle ?>"></li>
						<li><textarea name="content" rows="40" ><?php echo $originalContent ?></textarea></li>
						<li><input type="hidden"  name="post_id"  value="<?php echo $_GET['id'] ?>"></li>
						<li><input type="text" name="tags" value="<?php echo $tags  ?>" ></li>
						<li><input type="submit" name="submit" value="VALIDER"></li>
					</ul>
				</form>

		</article>


	</div>
</body>
</html>