<!DOCTYPE html>
<html lang="fr">
<head>
	<meta charset="UTF-8">
	<title>Mon Blog</title>
	<link rel="stylesheet" href="styles.css">
	<link href='http://fonts.googleapis.com/css?family=Droid+Serif' rel='stylesheet' type='text/css'>
</head>
<body>
	<div>

		<?php include "nav.php" ?>

		<h1><a href="index.php">Sciences politiques <br>& Économie générale</a></h1>
		<article>
			<ul>
				
				<?php foreach ($slicePosts as $post) : ?>

					<li><h2><a href="post.php?id=<?php echo $post["id"] ?>"><?php echo $post["title"] ?></a></h2></li>

					<li>Le <?php echo date("d/m/Y",strtotime($post["date_create"])) ?> / Commentaires : <?php echo $comments->getNumberOfComments($post["id"]) ?></li>

					<li>Par <?php echo $posts->getAuthorName($post["id"]) ?></li>

					<?php $tags = explode(",",$posts->getTags($post["id"])) ?>

					<?php if($tags[0] != ""): ?>
					<li>
						<?php foreach($tags as $tag): ?>

							<a href="tag.php?tag=<?php echo $tag ?>" ><span class="tag"><?php echo $tag ?></a></span>

						<?php endforeach ?>
					</li>
					<?php endif ?>
					
				


					<?php if ($post["image_name"]) : ?>
						<li><img src="pictures/<?php echo $post["image_name"]; ?>"/></li>
					<?php endif; ?>

					<li><?php echo postExtract($post) ?>... </li>
					
					<li><a href="post.php?id=<?php echo $post["id"] ?>">+ Lire la suite</a></li>
					
					<hr>
				<?php endforeach ?>
			</ul>
		</article>

		<nav>
			<?php if($page != 1): ?>
				<a href="index.php?page=<?php echo $page-1 ?>" class="green"> - les <?php echo POSTS_BY_PAGE ?> derniers posts</a>
			<?php endif; ?>
			<?php if($page < $numberOfPosts/POSTS_BY_PAGE): ?>
			<a href="index.php?page=<?php echo $page+1 ?>" class="green"> + les <?php echo POSTS_BY_PAGE ?> prochains posts</a>
			<?php endif; ?>
		</nav>
	</div>
</body>
</html>
