<!DOCTYPE html>
<html lang="fr">
<head>
	<meta charset="UTF-8">
	<title>Mon Blog</title>
	<link rel="stylesheet" href="styles.css">
	<link href='http://fonts.googleapis.com/css?family=Droid+Serif' rel='stylesheet' type='text/css'>
</head>
<body>
	<div>

		<h1><a href="index.php">Sciences politiques <br>& Économie générale</a></h1>
		<br>
		<h2>Se connecter</h2>
		<br>
		<form action="login.php" method="post">
			<ul>
				<li>Nom d'utilisateur : <input type="text" name="name" required></li>
				<li>Mot de passe : <input type="password" name="password" required></li>
				<li><input type="submit" name="submit" value="VALIDER"</li>
				<?php echo $error; ?>
			</ul>
		</form>

	</div>
</body>
</html>