<!DOCTYPE html>
<html lang="fr">
<head>
	<meta charset="UTF-8">
	<title>Mon Blog</title>
	<link rel="stylesheet" href="styles.css">
	<link href='http://fonts.googleapis.com/css?family=Droid+Serif' rel='stylesheet' type='text/css'>
</head>
<body>
	<div>
		<h1>Se Connecter</h1>
		<form action="login.php" method="post">
			<ul>
				<li>Nom d'utilisateur : <input type="text" name="name"></li>
				<li>Mot de passe : <input type="password" name="password"></li>
				<li><input type="submit" name="submit" value="VALIDER"</li>
			</ul>
		</form>
	</div>
</body>
</html>