<!DOCTYPE html>
<html lang="fr">
<head>
	<meta charset="UTF-8">
	<title>Mon Blog</title>
	<link rel="stylesheet" href="styles.css">
	<link href='http://fonts.googleapis.com/css?family=Droid+Serif' rel='stylesheet' type='text/css'></head>
<body>
	<div>
		<h1><a href="index.php">Sciences politiques <br>& Économie générale</a></h1>
		<article>
			<ul>
				<li><h2><?php echo $myPost["title"] ?></h2></li>
				<li>Auteur : <?php echo $post->getAuthorName($myPost["id"]) ?></li>
				<li>Date de création : <?php echo $myPost["date_create"] ?></li>
				<li><?php echo $myPost["content"] ?></li>
			</ul>
			<hr>
			<ul>
				<li>Commentaires :</li>
				<?php foreach ($allComments as $comment) : ?>
					<li><?php echo str_replace("\r", "<br />", $comment["content"]) ?></li>
					<li>De : <?php echo $post->getAuthorCommentName($comment["id"]) ?>, le <?php echo $comment["date"] ?></li>
				<?php endforeach ?>
			</ul>
		</article>
		<a href="index.php">Revenir à l'accueil</a>
	</div>
</body>
</html>