<!DOCTYPE html>
<html lang="fr">
<head>
	<meta charset="UTF-8">
	<title>Mon Blog</title>
	<link rel="stylesheet" href="styles.css">
	<link href='http://fonts.googleapis.com/css?family=Droid+Serif' rel='stylesheet' type='text/css'>
</head>
<body>
	<div>
		<h1>S'inscrire</h1>
		<form action="register.php" method="post">
			<ul>
				<li>Nom d'utilisateur : <input type="text" name="name"></li>
				<li>Mot de passe : <input type="password" name="password"></li>
				<li>Confirmation du mot de passe : <input type="password" name="password2"></li>
				<!-- <li>
					<input type="radio" name="statut" value="author" id="author" class="radio" /> <label for="author">Auteur</label><br />
					<input type="radio" name="statut" value="visitor" id="visitor" class="radio" checked /> <label for="visitor">Visiteur</label>
				</li> -->
				<li><input type="submit" name="submit" value="VALIDER"></li>
				<?php echo $message ?>
			</ul>
		</form>

	</div>
</body>
</html>